### ISSUE TITLE
Can't compute on readable values?

### ISSUE THREAD

**Issue by maconard** [grencez/protocon#15]
I'm expecting to be able to have a process compute on the values it can read. Is this not actually possible?

Relevant code:
```
constant N := 3;
constant X := 20;
constant Y := 20;

variable x[N] < X;
variable y[N] < Y;

...

process P[i < N]
{
  // Can read/write its position
  read: x[i], y[i];
  write: x[i], y[i];

  // Compute data position
  let z := x[i] + X*y[i]; // Error, message literally just says "Error on line #"
  
  ...
}
```

Cheers,

**Comment by grencez** [comment]
`let` values can only be derived from and used as indices... perhaps it should be renamed for clarity?

This is because (1) the tool only supports static topologies and (2) processes with the same name must act the same way, regardless of their id/index.

This hasn't been a huge problem due to the nature of adding convergence, which is essentially to "get to a good state by any means necessary". For example, what will prevent a process from simply zeroizing `x[i]` and `y[i]` to make `z==0` as well?

**Comment by maconard** [comment]
I understand. Thank you for your responses!
